import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server.mjs';
import { openDB } from '../lib/db.mjs';

test('end-to-end: import → classification → 14-day plan → checkin → mutual buddy feedback → revocation', async t => {
  const temp = mkdtempSync(join(tmpdir(), 'shizhi-test-'));
  const dbPath = join(temp, 'app.sqlite');
  const app = createApp({ dbPath, aiKey: '' }); app.server.listen(0, '127.0.0.1'); await once(app.server, 'listening');
  const base = `http://127.0.0.1:${app.server.address().port}`; app.config.origin = base;
  t.after(async () => { app.server.closeAllConnections(); await new Promise(resolve => app.server.close(resolve)); app.db.close(); rmSync(temp, { recursive: true, force: true }); });
  const jars = {};
  async function request(who, path, body, method = 'POST', extra = {}) {
    const res = await fetch(base + '/api' + path, { method: body === undefined ? 'GET' : method,
      headers: { Origin: base, Cookie: jars[who] || '', 'Content-Type': 'application/json', ...extra }, body: body === undefined ? undefined : JSON.stringify(body) });
    if (res.headers.get('set-cookie')) jars[who] = res.headers.get('set-cookie').split(';')[0];
    return { status: res.status, body: await res.json(), headers: res.headers };
  }
  const user = async name => {
    const r = await request(name, '/register', { username: `test_${name}`, password: 'Test-only-Pass-2026', nickname: name }); assert.equal(r.status, 200); assert.ok(r.headers.get('set-cookie').includes('HttpOnly')); assert.ok(!('password' in r.body.user)); return r.body.user;
  };
  const alice = await user('alice'); const bob = await user('bob'); await user('eve');
  assert.equal((await request('anonymous', '/dashboard')).status, 401);
  assert.equal((await request('alice', '/import', { consent: true, items: [] }, 'POST', { Origin: 'https://evil.example' })).status, 403);
  const items = Array.from({ length: 30 }, (_, i) => ({ title: `摄影构图 ${i + 1}`, url: `https://zhuanlan.zhihu.com/p/${100000 + i}`, excerpt: '摄影中的自然光与构图练习', collection: '摄影收藏夹' }));
  assert.equal((await request('alice', '/import', { items })).status, 400);
  assert.equal((await request('alice', '/import', { consent: true, items: [...items, { title: 'bad', url: 'https://evil.example' }] })).status, 400);
  assert.equal((await request('alice', '/dashboard')).body.items.length, 0, 'invalid batch is atomic');
  assert.equal((await request('alice', '/import', { consent: true, items })).body.imported, 30);
  assert.equal((await request('alice', '/import', { consent: true, items })).body.duplicates, 30);
  assert.equal((await request('bob', '/dashboard')).body.items.length, 0, 'private collections stay isolated');
  assert.equal((await request('alice', '/analyze', { engine: 'ai' })).status, 400, 'AI cannot transmit without setup and consent');
  assert.equal((await request('alice', '/analyze', { engine: 'local' })).body.count, 30);
  const insight = (await request('alice', '/dashboard')).body.insights[0]; assert.equal(insight.topic, '摄影'); assert.equal(insight.count, 30); assert.equal(insight.candidate, true);
  const c = (await request('alice', '/challenges', { topic: '摄影', minutes: 30, engine: 'local' })).body.id; assert.ok(c);
  assert.equal((await request('alice', '/challenges', { topic: '摄影', minutes: 30, engine: 'local' })).status, 409);
  const challenge = (await request('alice', '/dashboard')).body.challenges[0]; assert.equal(challenge.days.length, 14);
  assert.equal((await request('bob', '/checkin', { challenge_id: c, day: 1 })).status, 404);
  assert.equal((await request('alice', '/checkin', { challenge_id: c, day: 14 })).status, 400);
  assert.equal((await request('alice', '/checkin', { challenge_id: c, day: 1, review_done: true, reflection: '太短' })).status, 400);
  const k = { challenge_id: c, day: 1, read_done: true, practice_done: true, review_done: true, reflection: '我比较了不同光线中的主体，下一次会简化背景。', shared: true };
  const check = (await request('alice', '/checkin', k)).body.id;
  assert.equal((await request('alice', '/checkin', { ...k, artifact: 'data:image/png;base64,YmFk' })).status, 400);
  const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=';
  assert.equal((await request('alice', '/checkin', { ...k, artifact: png })).status, 200);
  assert.equal((await request('alice', '/checkin', k)).body.id, check, 'upsert one checkin per day');
  assert.equal((await request('alice', `/checkin?id=${check}`)).body.checkin.artifact, png, 'editing text preserves the saved image');
  assert.equal((await request('alice', '/dashboard')).body.challenges[0].completed, 1);
  assert.equal((await request('bob', `/checkin?id=${check}`)).status, 404);
  const profile = nickname => ({ nickname, topic: '摄影', level: '入门', slot: '晚上', timezone: 'Asia/Shanghai', discoverable: true, ai_consent: false });
  await request('alice', '/profile', profile('alice')); await request('bob', '/profile', profile('bob'));
  assert.equal((await request('bob', '/buddies')).body.candidates[0].score, 100);
  const invitation = (await request('bob', '/buddy-request', { recipient: alice.id })).body.id; assert.ok(invitation);
  assert.equal((await request('bob', '/buddy-respond', { id: invitation, status: 'accepted' })).status, 403);
  assert.equal((await request('alice', '/buddy-request', { recipient: bob.id })).status, 409);
  assert.equal((await request('alice', '/buddy-respond', { id: invitation, status: 'accepted' })).status, 200);
  assert.equal((await request('bob', '/buddies')).body.feed.length, 1);
  assert.equal((await request('bob', `/checkin?id=${check}`)).status, 200);
  assert.equal((await request('eve', `/checkin?id=${check}`)).status, 404);
  assert.equal((await request('eve', '/feedback', { checkin_id: check, body: '越权评论' })).status, 403);
  assert.equal((await request('bob', '/feedback', { checkin_id: check, body: '可以试试侧光，看看主体的层次是否更明显。' })).status, 200);
  assert.equal((await request('alice', `/checkin?id=${check}`)).body.feedback.length, 1);
  await request('alice', '/checkin', { ...k, shared: false });
  assert.equal((await request('bob', `/checkin?id=${check}`)).status, 404, 'unsharing revokes access');
  await request('alice', '/checkin', k);
  const reopened = openDB(dbPath); assert.equal(reopened.prepare('SELECT count(*) AS n FROM items').get().n, 30); reopened.close();
  await request('alice', '/buddy-respond', { id: invitation, status: 'blocked' });
  assert.equal((await request('bob', `/checkin?id=${check}`)).status, 404, 'blocking revokes access');
  assert.equal((await request('bob', '/buddy-request', { recipient: alice.id })).status, 409);
  assert.equal((await request('alice', '/data', { confirm: '清除学习数据' }, 'DELETE')).status, 200);
  const after = (await request('alice', '/dashboard')).body;
  assert.equal(after.items.length, 0); assert.equal(after.challenges.length, 0); assert.equal(after.consents.length, 0);
  assert.equal((await request('bob', '/buddies')).body.feed.length, 0);
  assert.equal(app.db.prepare('SELECT count(*) AS n FROM feedback').get().n, 0);
  await request('alice', '/logout', {}); assert.equal((await request('alice', '/me')).status, 401);
});
